call plug#begin()

Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'preservim/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-airline/vim-airline'

call plug#end()

set backspace=indent,eol,start

syntax enable
colorscheme dracula

set directory=$HOME/.vim/swap//

let g:airline_powerline_fonts = 1
let g:airline_theme='dracula'
